site:
  access: '0.0.0.0'
  port: 8081
  username: 'cmills'
  password: '1234'
  token: ''

door:
  name: 'Home'
  relay_pin: 23
  state_pin: 17
  state_pin_closed_value: 0
  approx_time_to_close: 15
  approx_time_to_open: 15

config:
  use_auth: true
  use_alerts: true
  use_api: true
  user: 'Chad'
